Algoritmo "ler_dimensoes_retangulo"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicitar dimensões do retângulo, cacular e dizer a área
// Autor(a)    : Laryssa
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis 
base: real
altura: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Programa Área do Retângulo")
   Escreva("Digite o valor da base do retângulo :")
   Leia(base)
   Escreva("Digite o valor da altura do retângulo :")
   Leia(altura)
   area <- base * altura
   Escreva("A área do retângulo é :", area)

Fimalgoritmo