Algoritmo "sucessor"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler valor do teclado e escrever o sucessor
// Autor(a)    : Laryssa
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis
   numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um Numero: ")
Leia(numero)
numero<- numero + 1
Escreva ("O sucessor do seu numero é: ", numero)

Fimalgoritmo