Algoritmo "exercicio19"
// Disciplina  : (Lógica de Programação com JavaScript)
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler dois valores e escrever o maior deles
// Autor(a)    : Laryssa Daniela
// Data atual  : 31/08/2026
Var
   // Seção de Declarações das variáveis
   valor1: real
   valor2: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o primeiro valor a ser comparado")
   Leia(valor1)
   Escreval("Digite o segundo valor a ser comparado")
   Leia(valor2)
   se valor1 > valor2 entao
      Escreval("o maior valor é: ", valor1)
   senao
      Escreval ("o maior valor é: ", valor2)
   fimse

Fimalgoritmo